name: Android CI

on:
  pull_request:
    branches:
      - 'master'
      - 'develop'
      - 'feature/*'
      - 'bugfix/*'
  push:
    branches:
      - 'master'
      - 'develop'
      - 'feature/*'
      - 'bugfix/*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Tests
        run: ./gradlew test --stacktrace
      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk